---
- name: List all guests on proxmox cluster
  hosts: localhost
  gather_facts: no # This will not gather facts from the local host
  tasks:

  - name: Authenticate with Proxmox and get all guests
    community.general.proxmox_vm_info:
      api_user: 'root@pam'
      api_host: '{{ proxmox_api_host }}'
      api_token_id: '{{ proxmox_token_id | default(omit) }}'
      api_token_secret: '{{ proxmox_token_secret | default(omit) }}'
      validate_certs: no
    register: proxmox_vms

  - name: Print all guests
    debug:
      var: proxmox_vms