---
- name: prompt-example
  hosts: localhost
  vars_prompt: # This is the section where you can define the variables to be prompted
    - name: "var_name"
      prompt: "Your name please"
      private: no # This will show the input
    - name: "var_age"
      prompt: "Your age please"
      private: no
    - name: "var_secret"
      prompt: "Your secret please"
      private: yes # This will hide the input
    
  tasks:
    - name: "Print the name" # This is the task that will print the variables
      debug:
        msg: "Hello {{ var_name }}. You are {{ var_age }} years old and your secret is {{ var_secret }}."